/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIndexRouteImport } from './routes/property.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as PropertySlugRouteImport } from './routes/property.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AgentIdRouteImport } from './routes/agent.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIndexRoute = PropertyIndexRouteImport.update({
  id: '/property/',
  path: '/property/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIdRoute = AgentIdRouteImport.update({
  id: '/agent/$id',
  path: '/agent/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/agent/$id': typeof AgentIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/agent/': typeof AgentIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/property/': typeof PropertyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/agent/$id': typeof AgentIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/agent': typeof AgentIndexRoute
  '/blog': typeof BlogIndexRoute
  '/property': typeof PropertyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/agent/$id': typeof AgentIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/agent/': typeof AgentIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/property/': typeof PropertyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/agent/$id'
    | '/blog/$slug'
    | '/property/$slug'
    | '/agent/'
    | '/blog/'
    | '/property/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/agent/$id'
    | '/blog/$slug'
    | '/property/$slug'
    | '/agent'
    | '/blog'
    | '/property'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/agent/$id'
    | '/blog/$slug'
    | '/property/$slug'
    | '/agent/'
    | '/blog/'
    | '/property/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AgentIdRoute: typeof AgentIdRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PropertySlugRoute: typeof PropertySlugRoute
  AgentIndexRoute: typeof AgentIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PropertyIndexRoute: typeof PropertyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/': {
      id: '/property/'
      path: '/property'
      fullPath: '/property/'
      preLoaderRoute: typeof PropertyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$id': {
      id: '/agent/$id'
      path: '/agent/$id'
      fullPath: '/agent/$id'
      preLoaderRoute: typeof AgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AgentIdRoute: AgentIdRoute,
  BlogSlugRoute: BlogSlugRoute,
  PropertySlugRoute: PropertySlugRoute,
  AgentIndexRoute: AgentIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  PropertyIndexRoute: PropertyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
